version: '3'

services:
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - traefik

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web

  whoami1:
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.docker.localhost`)"

  whoami2:
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.docker.localhost`)"

    whoami3:
      image: containous/whoami
      networks:
        - web
      labels:
        - "traefik.http.routers.whoami3.rule=Host(`whoami3.docker.localhost`)"

  whoami4:
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami4.rule=Host(`whoami4.docker.localhost`)"

  whoami5:
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami5.rule=Host(`whoami5.docker.localhost`)"

networks:
  web:
    external: true
