version: '3'
services:
  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web

  nginx-proxy:
    image: "nginx:latest"
    ports:
      - "8081:80"

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  whoami1:
    image: "containous/whoami"
    labels:
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.yourdomain.com`)"

  whoami2:
    image: "containous/whoami"
    labels:
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.yourdomain.com`)"

  whoami3:
    image: "containous/whoami"
    labels:
      - "traefik.http.routers.whoami3.rule=Host(`whoami3.yourdomain.com`)"

networks:
  web:
    external: true
