version: '3'

services:
  traefik:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.docker.localhost`)"

  whoami2:
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.docker.localhost`)"

  whoami3:
    image: containous/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami3.rule=Host(`whoami3.docker.localhost`)"

  nginx-proxy:
    image: nginx
    networks:
      - web
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - whoami1
      - whoami2
      - whoami3

networks:
  web:
    external: true
