version: '3'

services:
  traefik:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: traefik/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.sticky=true"

  whoami2:
    image: traefik/whoami
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.sticky=true"

  # whoami3:
  #   image: traefik/whoami
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.http.routers.whoami.rule=Host(`localhost`)"
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"
  #     - "traefik.http.services.whoami.loadbalancer.sticky=true"

  # whoami4:
  #   image: traefik/whoami
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.http.routers.whoami.rule=Host(`localhost`)"   
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"   
  #     - "traefik.http.services.whoami.loadbalancer.sticky=true"

  # whoami5:
  #   image: traefik/whoami
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.http.routers.whoami.rule=Host(`localhost`)"   
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"   
  #     - "traefik.http.services.whoami.loadbalancer.sticky=true"

  # whoami6:
  #   image: traefik/whoami
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.http.routers.whoami.rule=Host(`localhost`)"   
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"   
  #     - "traefik.http.services.whoami.loadbalancer.sticky=true"

  # whoami7:
  #   image: traefik/whoami
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.http.routers.whoami.rule=Host(`localhost`)"   
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"   
  #     - "traefik.http.services.whoami.loadbalancer.sticky=true"

  # whoami8:
  #   image: traefik/whoami
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.http.routers.whoami.rule=Host(`localhost`)"   
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"   
  #     - "traefik.http.services.whoami.loadbalancer.sticky=true"

  # nginx-proxy:
  #   image: nginx
  #   networks:
  #     - web
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - whoami1
  #     - whoami2
  #     - whoami3

networks:
  web:
    external: true
